### ISSUE TITLE
Unsupported protocol scheme

### ISSUE THREAD

**Issue by Tomelin** [mrizkimaulidan/fabula#2]
Hi,

I'm using the fabula to scrap instagram but it is return this error:

golang version: go version go1.19 linux/amd64
command:  ./fabula  -username=john.doe

error:

2022/08/25 19:17:16 starting to scrape story from john.doe
2022/08/25 19:17:17 downloading, please wait.
2022/08/25 19:17:17 error when requesting to url: Get "#!": unsupported protocol scheme ""

What's the error?  How to adjust the problem?

**Comment by mrizkimaulidan** [comment]
Hi,

The error occurred when scraping the story URL from scraping process, but the scraped URL result giving the wrong URL. I do some debugging on my local, this must be from their website problem.

The main problem is the application cannot scraping the HTML tag correctly.

I have do some debugging and fixing, but still no luck.

This application are not working anymore until I found how to fix it.

**Comment by mrizkimaulidan** [comment]
Hi,

This application should be working now, I'm rewriting all of the source code.

Thanks.
